### ISSUE TITLE
gzip, ng-universal, lazy load off-screen images,  y ngx-meta. Herramientas para mejorar tu SEO score

### ISSUE THREAD

**Issue by FelipeLujan** [angular-medellin/meetup#121]
# Me gustaría...

* [x] 😎 Ser el próximo speaker
* [ ] 🤠 Publicar mi solución al Angular Challenge
* [ ] 😊 Escribir un artículo en el Blog
* [ ] 😇 Dar feedback
* [ ] 😋 Otro

## Descripción
- 💬 Dado que google ha anunciado que próximamente implementará cambios en sus parámetros para rankear sitios web. Quisiera compartir con la comunidad angular varias herramientas que nos ayudarán a estar bien posicionados en resultados de búsqueda. Grado de complejidad: bajo.
Analizaremos la efectividad de estas herramientas por medio de las herramientas de desarrollo incorporadas en google chome (Lighthouse).
Estas herrmientas son gzip, ng-universal, lazy load off-screen images,  y ngx-meta

- ⏰ 40 minutos creo que duraría la charla

**Comment by jdjuan** [comment]
Súper @FelipeLujan ! 😁 Qué buen tema! Muy necesario 👍 

No olvides echarle un ojo a nuestros **[Speaker Guidelines](https://github.com/angular-medellin/meetup/blob/master/assets/1.%20meetups/SPEAKERS.md#-speakers-)** para que la saques del estadio 🎉 

Envíame tus diapositivas cuando estén listas para darte feedback! ⚡️
